ROOMS = {
    "room_1": {
        "name": "Study",
        "description": "A dusty study with a fireplace and a portrait.",
        "exits": {"north": "room_2"},
        "monsters": ["ghost"],
        "items": [
            {"name": "rusty key",        "hidden": False, "revealed_by": None},
            {"name": "old book",         "hidden": False, "revealed_by": None},
            {"name": "magnifying glass", "hidden": False, "revealed_by": None},
            {"name": "quill pen",        "hidden": False, "revealed_by": None},
            {"name": "secret letter",    "hidden": True,  "revealed_by": "old book"},
        ],
        "npcs": [
            {
                "name": "Professor Aldric",
                "description": "A frail old man hunched over a desk, scribbling notes by candlelight.",
                "personality": "Speaks in riddles, knows secrets about the mansion, cryptic but helpful if you earn his trust.",
                "knowledge": "Knows about the ghost, the secret letter behind the old book, and that the rusty key opens something in the basement.",
                "can_search_web": False,
            },
            {
                "name": "The Oracle",
                "description": "A mysterious figure hunched over a glowing crystal ball, muttering about distant lands.",
                "personality": "Speaks with authority on matters of the outside world. Dry, precise, and occasionally sardonic.",
                "knowledge": "Has an uncanny knowledge of American politics, current events, and world affairs.",
                "can_search_web": True,
            },
        ],
    },
    "room_2": {
        "name": "Hallway",
        "description": "A narrow hallway lined with cracked mirrors.",
        "exits": {"south": "room_1", "east": "room_3", "west": "room_4", "north": "room_5"},
        "monsters": [],
        "items": [],
        "npcs": [],
    },
    "room_3": {
        "name": "Kitchen",
        "description": "A decaying kitchen with rusted utensils and a faint smell of rot.",
        "exits": {"west": "room_2", "north": "room_6"},
        "monsters": ["giant rat"],
        "items": [
            {"name": "knife",               "hidden": False, "revealed_by": None},
            {"name": "loaf of stale bread", "hidden": False, "revealed_by": None},
        ],
        "npcs": [],
    },
    "room_4": {
        "name": "Library",
        "description": "Tall shelves filled with ancient, crumbling books. A ladder rests against one shelf.",
        "exits": {"east": "room_2", "north": "room_7"},
        "monsters": ["shadow"],
        "items": [
            {"name": "ancient tome", "hidden": False, "revealed_by": None},
            {"name": "candle",       "hidden": False, "revealed_by": None},
            {"name": "hidden note",  "hidden": True,  "revealed_by": "ancient tome"},
        ],
        "npcs": [],
    },
    "room_5": {
        "name": "Grand Foyer",
        "description": "A vast foyer with a chandelier swaying slightly above. The front door is sealed shut.",
        "exits": {"south": "room_2", "north": "room_8"},
        "monsters": [],
        "items": [
            {"name": "silver coin", "hidden": False, "revealed_by": None},
        ],
        "npcs": [],
    },
    "room_6": {
        "name": "Pantry",
        "description": "A cramped pantry with empty shelves and scattered jars.",
        "exits": {"south": "room_3"},
        "monsters": ["spider swarm"],
        "items": [
            {"name": "glass jar",   "hidden": False, "revealed_by": None},
            {"name": "poison vial", "hidden": True,  "revealed_by": "glass jar"},
        ],
        "npcs": [],
    },
    "room_7": {
        "name": "Secret Room",
        "description": "A hidden chamber behind the bookshelf, filled with strange symbols.",
        "exits": {"south": "room_4"},
        "monsters": ["wraith"],
        "items": [
            {"name": "strange amulet", "hidden": False, "revealed_by": None},
            {"name": "ritual dagger",  "hidden": True,  "revealed_by": "strange amulet"},
        ],
        "npcs": [],
    },
    "room_8": {
        "name": "Dining Hall",
        "description": "A long dining table covered in dust, set as if awaiting guests who never came.",
        "exits": {"south": "room_5", "east": "room_9", "west": "room_10"},
        "monsters": ["vampire"],
        "items": [
            {"name": "golden goblet", "hidden": False, "revealed_by": None},
            {"name": "invitation",    "hidden": True,  "revealed_by": "golden goblet"},
        ],
        "npcs": [],
    },
    "room_9": {
        "name": "Garden",
        "description": "An overgrown garden under a dark sky. The air is eerily still.",
        "exits": {"west": "room_8"},
        "monsters": ["werewolf"],
        "items": [
            {"name": "herbs",         "hidden": False, "revealed_by": None},
            {"name": "silver bullet", "hidden": True,  "revealed_by": "herbs"},
        ],
        "npcs": [],
    },
    "room_10": {
        "name": "Basement Stairs",
        "description": "A creaky staircase leading down into darkness.",
        "exits": {"east": "room_8", "down": "room_11"},
        "monsters": [],
        "items": [],
        "npcs": [],
    },
    "room_11": {
        "name": "Basement",
        "description": "A damp basement with chains on the walls and a cold draft.",
        "exits": {"up": "room_10"},
        "monsters": ["ghoul"],
        "items": [
            {"name": "iron key",     "hidden": False, "revealed_by": None},
            {"name": "broken chain", "hidden": False, "revealed_by": None},
            {"name": "locket",       "hidden": True,  "revealed_by": "broken chain"},
        ],
        "npcs": [],
    },
}