ROOMS = {
    "room_1": {
        "name": "Study",
        "description": "A dusty study with a fireplace and a portrait.",
        "exits": {"north": "room_2"},
        "items": ["rusty key", "old book", "magnifying glass", "quill pen"],
        "monsters": ["ghost"],
    },
    "room_2": {
        "name": "Hallway",
        "description": "A narrow hallway lined with cracked mirrors.",
        "exits": {"south": "room_1", "east": "room_3", "west": "room_4", "north": "room_5"},
        "items": [],
        "monsters": [],
    },
    "room_3": {
        "name": "Kitchen",
        "description": "A decaying kitchen with rusted utensils and a faint smell of rot.",
        "exits": {"west": "room_2", "north": "room_6"},
        "items": ["knife", "loaf of stale bread"],
        "monsters": ["giant rat"],
    },
    "room_4": {
        "name": "Library",
        "description": "Tall shelves filled with ancient, crumbling books. A ladder rests against one shelf.",
        "exits": {"east": "room_2", "north": "room_7"},
        "items": ["ancient tome", "candle"],
        "monsters": ["shadow"],
    },
    "room_5": {
        "name": "Grand Foyer",
        "description": "A vast foyer with a chandelier swaying slightly above. The front door is sealed shut.",
        "exits": {"south": "room_2", "north": "room_8"},
        "items": ["silver coin"],
        "monsters": [],
    },
    "room_6": {
        "name": "Pantry",
        "description": "A cramped pantry with empty shelves and scattered jars.",
        "exits": {"south": "room_3"},
        "items": ["glass jar"],
        "monsters": ["spider swarm"],
    },
    "room_7": {
        "name": "Secret Room",
        "description": "A hidden chamber behind the bookshelf, filled with strange symbols.",
        "exits": {"south": "room_4"},
        "items": ["strange amulet"],
        "monsters": ["wraith"],
    },
    "room_8": {
        "name": "Dining Hall",
        "description": "A long dining table covered in dust, set as if awaiting guests who never came.",
        "exits": {"south": "room_5", "east": "room_9", "west": "room_10"},
        "items": ["golden goblet"],
        "monsters": ["vampire"],
    },
    "room_9": {
        "name": "Garden",
        "description": "An overgrown garden under a dark sky. The air is eerily still.",
        "exits": {"west": "room_8"},
        "items": ["herbs"],
        "monsters": ["werewolf"],
    },
    "room_10": {
        "name": "Basement Stairs",
        "description": "A creaky staircase leading down into darkness.",
        "exits": {"east": "room_8", "down": "room_11"},
        "items": [],
        "monsters": [],
    },
    "room_11": {
        "name": "Basement",
        "description": "A damp basement with chains on the walls and a cold draft.",
        "exits": {"up": "room_10"},
        "items": ["iron key", "broken chain"],
        "monsters": ["ghoul"],
    },
}